### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by Frankenstein666** [khalti/khalti-sdk-ios#1]
Please update your sdk for swift 4 I get
`Use of unresolved identifier 'NSForegroundColorAttributeName'`
I don't want to have to integrate the sdk manually instead of cocoapods.

**Comment by rjndra** [comment]
Will update very soon. For now you can set build version in pods section to swift 3,3.2 or 3.3.

**Comment by rjndra** [comment]
@Frankenstein666 Updated to version 1.0.9 supporting both swift 3 and 4.
