### ISSUE TITLE
Khalti.shared.action obj c implementation

### ISSUE THREAD

**Issue by andreshsingh** [khalti/khalti-sdk-ios#5]
The [document](https://docs.khalti.com/checkout/ios/#requirements) says that Khalti.shared.action is required to complete action after ebanking and card payment.

But the [example](https://github.com/khalti/khalti-sdk-ios/blob/master/Example%20Obj-c/Khalti-Pay/AppDelegate.m) doesnt have info about it.

Can you guys help me out ? 

khalti ios sdk version: 1.0.17

**Comment by rjndra** [comment]
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    **Khalti.shared.action(with: url)**
    return Khalti.shared.defaultAction() // Or true
}

**Comment by andreshsingh** [comment]
@rjndra the snippet you shared is of swift... there is no objective c implementation of the code...If i try to do something similar, i get an error...

![Screen Shot 2021-06-07 at 7 49 40 PM](https://user-images.githubusercontent.com/30138390/121030903-a07f8e00-c7c9-11eb-82e6-7d26ff3b3b5e.png)

**Comment by rjndra** [comment]
Try with clearing derived data and check the existence of action method in khalti sdk.

**Comment by rjndra** [comment]
Missing ; of your code might be cause of issue.

**Comment by andreshsingh** [comment]
hey @rjndra , i just tried in the example from the repo and it doesnt work there as well...
<img width="1351" alt="Screen Shot 2021-06-07 at 9 45 47 PM" src="https://user-images.githubusercontent.com/30138390/121052318-fceaa980-c7d9-11eb-98dd-bda06b69e885.png">

**Comment by rjndra** [comment]
Have you resolved issue or still stuck on this.

**Comment by andreshsingh** [comment]
Still stuck...

**Comment by rjndra** [comment]
Please use this as objc Code
```
if (Khalti.shared.canOpenUrl) {
        [Khalti.shared actionWith:url];
    }
```
